services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=events,lambda,logs
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=us-east-1
      - EVENT_BUS_NAME=data-sync-event-bus
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - NODE_ENV=development
    depends_on:
      - localstack
    volumes:
      - ./user-service/src:/app/src

  sqs-consumer:
    build: ./sqs-consumer
    container_name: sqs-consumer
    environment:
      - AWS_REGION=us-east-1
      - SQS_URL=http://localstack:4566/000000000000/user-events-queue
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack
